modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "soundsilence"
version = "${version}"
displayName = "SoundSilence"
authors = "Swerrio"
description = '''
A mod that allows you to completely turn off game sounds with one key
'''
#logoFile = ""

[[dependencies.soundsilence]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.soundsilence]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.6,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.soundsilence]]
modId = "architectury"
type = "required"
versionRange = "[17.0.6,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "soundsilence.mixins.json"
